### ISSUE TITLE
How to supply my own docker-compose.yml for localstack setup

### ISSUE THREAD

**Issue by cmeadowscb** [KozelAnatoliy/routineless#46]
I am in an environment where I need to supply localstack with a custom certificate authority.  I am able to start it manually using a docker-compose.yml file; however, from your docs I've not been able to figure out if your localstack runner can be set to use my docker-compose or to use the container that is already running by the same container name as I have in the project.json target specification.  

Please let me know if this is possible and, if so, how.

**Comment by cmeadowscb** [comment]
Also, I'm using localstack-pro rather than the open source version.  If I'm reading the status check command correctly it won't ever recognize my running instance because it's looking for only localstack/localstack.  Is this correct?

**Comment by KozelAnatoliy** [comment]
That is correct, it is looking for non pro localstack instance. Let me open a feature request, and I will implement lookup by container name and custom compose file provisioning as well.

**Comment by cmeadowscb** [comment]
Awesome!  Thank you.

**Comment by KozelAnatoliy** [comment]
Implemented and released in 1.2.0
