### ISSUE TITLE
Issues with documentation

### ISSUE THREAD

**Issue by triwats** [KozelAnatoliy/routineless#56]
* Fixing a few small issues with documentation

1. Fix Package README link
2. Fix incorrect parameter name

**Comment by triwats** [comment]
Not sure if you've used something @KozelAnatoliy to generate the schema/readme or if they're done manually? Lemme know, I can edit the PR directly. Cheers for the work so far 😉!

**Comment by KozelAnatoliy** [comment]
Thank you, will take a look soon!
